import Head from 'next/head'
import React from 'react'

const icons = () => {
    return (
        <div>
            <Head>
                <title>Company-icons</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/2083/2083417.png" />
            </Head>
            icons
        </div>
    )
}

export default icons
