import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import db from "../db";
import Cards from '../Components/Cards';
import Subscribe from '../Components/Subscribe';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Company</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/2083/2083417.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.cardContainer} >
        {
          db.map((e,i)=>(
           
            <Cards imageURL={e.imageURL} featured={e.featured} category={e.category} timeReq={e.timeReq} title={e.title} desc={e.desc} />
          ))
        }
        
        </div>
          <Subscribe/>
        <div className={styles.cardContainer} >
        {
          db.map((e,i)=>(
           
            <Cards imageURL={e.imageURL} featured={e.featured} category={e.category} timeReq={e.timeReq} title={e.title} desc={e.desc} />
          ))
        }
        
        </div>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
