import Head from 'next/head'
import React from 'react'

const theme = () => {
    return (
        
        <div>
             <Head>
        <title>Company-theme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/2083/2083417.png" />
      </Head>
            theme            
        </div>
    )
}

export default theme
